import { definePalette } from './_schema.mjs';

// Upper Rank Three. The magenta of his hair is the accent; the blue of his
// tattoos goes to keywords and the yellow of his eyes to functions. High
// contrast, no half measures — like the Destructive Death technique.
export default definePalette({
  id: 'akaza',
  label: 'Demon Slayer — Akaza',
  type: 'dark',

  ui: {
    bg: '#171320',
    bgDeep: '#0F0C16',
    bgAlt: '#1F1A2B',
    bgElevated: '#282237',
    fg: '#EAE4F0',
    fgMuted: '#AEA3BE',
    fgSubtle: '#8A7E9B',
    border: '#302943',
    accent: '#FF6BA8',
    accentAlt: '#5AA8E8',
    selection: '#452F52',
    lineHighlight: '#1F1A2B',
    cursor: '#FF6BA8',
    error: '#F05A6B',
    warning: '#F0C46B',
    info: '#5AA8E8',
    success: '#7FE0C4',
    added: '#7FE0C4',
    modified: '#5AA8E8',
    removed: '#F05A6B',
    ignored: '#6B6180',
  },

  ansi: {
    black: '#0F0C16',
    red: '#F05A6B',
    green: '#7FE0C4',
    yellow: '#F0C46B',
    blue: '#5AA8E8',
    magenta: '#FF6BA8',
    cyan: '#8FE0D9',
    white: '#D6CEE2',
    brightBlack: '#8A7E9B',
    brightRed: '#FF8090',
    brightGreen: '#A3EBD6',
    brightYellow: '#F7D894',
    brightBlue: '#8AC4F2',
    brightMagenta: '#FF95C2',
    brightCyan: '#AFEBE5',
    brightWhite: '#F9F5FC',
  },

  syntax: {
    comment: '#8F8399',
    keyword: '#5AA8E8',
    storage: '#5AA8E8',
    string: '#FF8FB8',
    stringEscape: '#F0C46B',
    number: '#B08FF0',
    constant: '#B08FF0',
    function: '#F0C46B',
    variable: '#EAE4F0',
    parameter: '#C9C0D6',
    property: '#E8B8CE',
    class: '#7FE0D9',
    type: '#7FE0D9',
    operator: '#AEA3BE',
    punctuation: '#9A8FAB',
    tag: '#5AA8E8',
    attribute: '#FF6BA8',
    regexp: '#7FE0C4',
    decorator: '#FF6BA8',
    invalid: '#F05A6B',
  },
});
