import { definePalette } from './_schema.mjs';

// Upper Rank Six, the brother. Sickly green in the background and in strings,
// blood orange of his sickles in keywords and the yellow of his hair tips in
// functions. Uncomfortable on purpose — never at the cost of legibility.
export default definePalette({
  id: 'gyutaro',
  label: 'Demon Slayer — Gyutaro',
  type: 'dark',

  ui: {
    bg: '#12160F',
    bgDeep: '#0B0E09',
    bgAlt: '#1A1F15',
    bgElevated: '#22281C',
    fg: '#E2E8DA',
    fgMuted: '#9EAC93',
    fgSubtle: '#7C8A71',
    border: '#28301F',
    accent: '#B8D95A',
    accentAlt: '#E86B3D',
    selection: '#3A4429',
    lineHighlight: '#1A1F15',
    cursor: '#B8D95A',
    error: '#E85D4F',
    warning: '#E8C45A',
    info: '#7FC4B8',
    success: '#8FD97F',
    added: '#8FD97F',
    modified: '#7FC4B8',
    removed: '#E85D4F',
    ignored: '#616E57',
  },

  ansi: {
    black: '#0B0E09',
    red: '#E85D4F',
    green: '#B8D95A',
    yellow: '#E8C45A',
    blue: '#7FC4B8',
    magenta: '#D98FA0',
    cyan: '#9FD9C9',
    white: '#CBD4BF',
    brightBlack: '#7C8A71',
    brightRed: '#F58272',
    brightGreen: '#CBE885',
    brightYellow: '#F2D687',
    brightBlue: '#A3D9CE',
    brightMagenta: '#E8AFBC',
    brightCyan: '#BCE8DD',
    brightWhite: '#F3F7EE',
  },

  syntax: {
    comment: '#87957C',
    keyword: '#E86B3D',
    storage: '#E86B3D',
    string: '#B8D95A',
    stringEscape: '#E8C45A',
    number: '#7FC4B8',
    constant: '#7FC4B8',
    function: '#E8C45A',
    variable: '#E2E8DA',
    parameter: '#C0CBB4',
    property: '#CBD9A0',
    class: '#D98FA0',
    type: '#D98FA0',
    operator: '#9EAC93',
    punctuation: '#8D9B82',
    tag: '#E86B3D',
    attribute: '#B8D95A',
    regexp: '#9FD9C9',
    decorator: '#E8C45A',
    invalid: '#E85D4F',
  },
});
