import { definePalette } from './_schema.mjs';

// Her hair gradient is the whole theme: pink at the root, green at the tip. The
// pink is the accent and the strings; the green takes the keywords, inverting
// the usual. A lighter plum background so the gold of her uniform survives.
export default definePalette({
  id: 'mitsuri',
  label: 'Demon Slayer — Mitsuri Kanroji',
  type: 'dark',

  ui: {
    bg: '#20161C',
    bgDeep: '#170F14',
    bgAlt: '#291D25',
    bgElevated: '#33252E',
    fg: '#F7E6EE',
    fgMuted: '#C4A5B5',
    fgSubtle: '#9C7C8C',
    border: '#412E3A',
    accent: '#FF8FB8',
    accentAlt: '#7FD98F',
    selection: '#54324A',
    lineHighlight: '#291D25',
    cursor: '#FF8FB8',
    error: '#F2555F',
    warning: '#F5D07E',
    info: '#A8C4F0',
    success: '#7FD98F',
    added: '#7FD98F',
    modified: '#A8C4F0',
    removed: '#F2555F',
    ignored: '#806371',
  },

  ansi: {
    black: '#170F14',
    red: '#F2555F',
    green: '#7FD98F',
    yellow: '#F5D07E',
    blue: '#A8C4F0',
    magenta: '#FF8FB8',
    cyan: '#8FE0C4',
    white: '#E5D2DC',
    brightBlack: '#9C7C8C',
    brightRed: '#FF7B84',
    brightGreen: '#9FE5AB',
    brightYellow: '#FADFA3',
    brightBlue: '#C2D6F7',
    brightMagenta: '#FFACC9',
    brightCyan: '#A8EBD6',
    brightWhite: '#FEF4F9',
  },

  syntax: {
    comment: '#A08494',
    keyword: '#7FD98F',
    storage: '#7FD98F',
    string: '#FFAFC9',
    stringEscape: '#F5D07E',
    number: '#C7A8F0',
    constant: '#C7A8F0',
    function: '#F5D07E',
    variable: '#F7E6EE',
    parameter: '#D9C2CE',
    property: '#EFC4D6',
    class: '#8FE0C4',
    type: '#8FE0C4',
    operator: '#C4A5B5',
    punctuation: '#AC8B9B',
    tag: '#7FD98F',
    attribute: '#FF8FB8',
    regexp: '#8FE0C4',
    decorator: '#F5D07E',
    invalid: '#F2555F',
  },
});
