import { definePalette } from './_schema.mjs';

// Mist: blue-grey instead of black, surfaces that hardly separate and an
// entirely pastel palette. The jade of his hair tips is the accent; the pale
// violet in keywords is the only edge in the theme.
export default definePalette({
  id: 'muichiro',
  label: 'Demon Slayer — Muichiro Tokito',
  type: 'dark',

  ui: {
    bg: '#1A1F21',
    bgDeep: '#141819',
    bgAlt: '#202628',
    bgElevated: '#283032',
    fg: '#E2EAEA',
    fgMuted: '#A0B0B0',
    fgSubtle: '#7F9192',
    border: '#2E3739',
    accent: '#9FD9D0',
    accentAlt: '#B0A8E0',
    selection: '#38494B',
    lineHighlight: '#202628',
    cursor: '#9FD9D0',
    error: '#E88A8A',
    warning: '#E0C48F',
    info: '#A8C8DE',
    success: '#A8D9B4',
    added: '#A8D9B4',
    modified: '#A8C8DE',
    removed: '#E88A8A',
    ignored: '#67797A',
  },

  ansi: {
    black: '#141819',
    red: '#E88A8A',
    green: '#A8D9B4',
    yellow: '#E0C48F',
    blue: '#A8C8DE',
    magenta: '#B0A8E0',
    cyan: '#9FD9D0',
    white: '#CBD6D6',
    brightBlack: '#7F9192',
    brightRed: '#F2A5A5',
    brightGreen: '#C2E8CB',
    brightYellow: '#EDD8AF',
    brightBlue: '#C4DCEE',
    brightMagenta: '#C9C2EE',
    brightCyan: '#BCE8E2',
    brightWhite: '#F4F8F8',
  },

  syntax: {
    comment: '#84979A',
    keyword: '#B0A8E0',
    storage: '#B0A8E0',
    string: '#A8D9B4',
    stringEscape: '#E0C48F',
    number: '#A8C8DE',
    constant: '#A8C8DE',
    function: '#E8E0C4',
    variable: '#E2EAEA',
    parameter: '#C2CFCF',
    property: '#BCD9D2',
    class: '#9FD9D0',
    type: '#9FD9D0',
    operator: '#A0B0B0',
    punctuation: '#8DA0A0',
    tag: '#B0A8E0',
    attribute: '#9FD9D0',
    regexp: '#E0C48F',
    decorator: '#E8E0C4',
    invalid: '#E88A8A',
  },
});
