import { definePalette } from './_schema.mjs';

// His heterochromia decides everything: gold in one eye, turquoise in the other
// — one becomes the accent, the other the strings. Scale-green black in the
// background, venom pink in keywords and Kaburamaru's white in types.
export default definePalette({
  id: 'obanai',
  label: 'Demon Slayer — Obanai Iguro',
  type: 'dark',

  ui: {
    bg: '#131614',
    bgDeep: '#0C0F0D',
    bgAlt: '#1A1E1B',
    bgElevated: '#222724',
    fg: '#E4E6EA',
    fgMuted: '#A0A5AD',
    fgSubtle: '#7F858F',
    border: '#2A2F2C',
    accent: '#E8C05A',
    accentAlt: '#4FD1C5',
    selection: '#3A4239',
    lineHighlight: '#1A1E1B',
    cursor: '#E8C05A',
    error: '#E86B7A',
    warning: '#E8C05A',
    info: '#7FB8D9',
    success: '#8FD9A8',
    added: '#8FD9A8',
    modified: '#7FB8D9',
    removed: '#E86B7A',
    ignored: '#666C75',
  },

  ansi: {
    black: '#0C0F0D',
    red: '#E86B7A',
    green: '#8FD9A8',
    yellow: '#E8C05A',
    blue: '#7FB8D9',
    magenta: '#D97F8F',
    cyan: '#4FD1C5',
    white: '#CFD3D9',
    brightBlack: '#7F858F',
    brightRed: '#F58A97',
    brightGreen: '#A8E5BC',
    brightYellow: '#F2D284',
    brightBlue: '#A0CDE8',
    brightMagenta: '#E89DA9',
    brightCyan: '#75E0D6',
    brightWhite: '#F5F7F9',
  },

  syntax: {
    comment: '#858B95',
    keyword: '#D97F8F',
    storage: '#D97F8F',
    string: '#4FD1C5',
    stringEscape: '#E8C05A',
    number: '#7FB8D9',
    constant: '#7FB8D9',
    function: '#E8C05A',
    variable: '#E4E6EA',
    parameter: '#BFC4CC',
    property: '#A8D9D0',
    class: '#C4CBBC',
    type: '#C4CBBC',
    operator: '#A0A5AD',
    punctuation: '#8C929C',
    tag: '#D97F8F',
    attribute: '#4FD1C5',
    regexp: '#8FD9A8',
    decorator: '#E8C05A',
    invalid: '#E86B7A',
  },
});
