import { definePalette } from './_schema.mjs';

// Reddened charcoal of a banked ember, with the orange of the flame as accent
// and the red of his hair tips in keywords. The gold of his eyes in strings;
// the smoke green is the only cool note, and it works as an anchor.
export default definePalette({
  id: 'rengoku',
  label: 'Demon Slayer — Kyojuro Rengoku',
  type: 'dark',

  ui: {
    bg: '#1C1210',
    bgDeep: '#130B09',
    bgAlt: '#241715',
    bgElevated: '#2E1E1A',
    fg: '#F5E5D5',
    fgMuted: '#BC9E8C',
    fgSubtle: '#96786A',
    border: '#3B2620',
    accent: '#FF8F3D',
    accentAlt: '#FFC24E',
    selection: '#5A2F1E',
    lineHighlight: '#241715',
    cursor: '#FF8F3D',
    error: '#FF5B4A',
    warning: '#FFC24E',
    info: '#9BCFCF',
    success: '#9BCF8F',
    added: '#9BCF8F',
    modified: '#9BCFCF',
    removed: '#FF5B4A',
    ignored: '#7A6154',
  },

  ansi: {
    black: '#130B09',
    red: '#FF5B4A',
    green: '#9BCF8F',
    yellow: '#FFC24E',
    blue: '#9BCFCF',
    magenta: '#E8B3A0',
    cyan: '#B5D9D4',
    white: '#DEC9B8',
    brightBlack: '#96786A',
    brightRed: '#FF8272',
    brightGreen: '#B5DEAB',
    brightYellow: '#FFD680',
    brightBlue: '#B5DEDE',
    brightMagenta: '#F2CBBC',
    brightCyan: '#CBE8E4',
    brightWhite: '#FFF5EA',
  },

  syntax: {
    comment: '#9C8071',
    keyword: '#FF5B4A',
    storage: '#FF5B4A',
    string: '#FFC24E',
    stringEscape: '#FF8F3D',
    number: '#9BCFCF',
    constant: '#9BCFCF',
    function: '#FF8F3D',
    variable: '#F5E5D5',
    parameter: '#D9C4B0',
    property: '#F0D4B8',
    class: '#E8B3A0',
    type: '#E8B3A0',
    operator: '#BC9E8C',
    punctuation: '#A88875',
    tag: '#FF5B4A',
    attribute: '#FF8F3D',
    regexp: '#E8B3A0',
    decorator: '#FFC24E',
    invalid: '#FF5B4A',
  },
});
