import { definePalette } from './_schema.mjs';

// Cold, cutting slate: the lilac of his eyes is the accent, the pale green of
// the wind goes to strings and the red of his scars to keywords. The contrast
// between surfaces is hard, with no middle ground.
export default definePalette({
  id: 'sanemi',
  label: 'Demon Slayer — Sanemi Shinazugawa',
  type: 'dark',

  ui: {
    bg: '#15181A',
    bgDeep: '#0D0F10',
    bgAlt: '#1C2023',
    bgElevated: '#24282C',
    fg: '#E4E8EA',
    fgMuted: '#9EA8AC',
    fgSubtle: '#7C888C',
    border: '#2B3034',
    accent: '#B5A8E0',
    accentAlt: '#9FD98F',
    selection: '#3A3E52',
    lineHighlight: '#1C2023',
    cursor: '#B5A8E0',
    error: '#E86B6B',
    warning: '#E8B87A',
    info: '#A8C4D9',
    success: '#9FD98F',
    added: '#9FD98F',
    modified: '#A8C4D9',
    removed: '#E86B6B',
    ignored: '#646E72',
  },

  ansi: {
    black: '#0D0F10',
    red: '#E86B6B',
    green: '#9FD98F',
    yellow: '#E8B87A',
    blue: '#A8C4D9',
    magenta: '#B5A8E0',
    cyan: '#9FD9CE',
    white: '#CDD4D6',
    brightBlack: '#7C888C',
    brightRed: '#F58787',
    brightGreen: '#B8E5AB',
    brightYellow: '#F2CE9E',
    brightBlue: '#C2D9E8',
    brightMagenta: '#CBC2EE',
    brightCyan: '#BCE8DF',
    brightWhite: '#F4F7F8',
  },

  syntax: {
    comment: '#818D91',
    keyword: '#E86B6B',
    storage: '#E86B6B',
    string: '#9FD98F',
    stringEscape: '#E8B87A',
    number: '#E8B87A',
    constant: '#E8B87A',
    function: '#C9BCF0',
    variable: '#E4E8EA',
    parameter: '#C0C8CB',
    property: '#BCCFC4',
    class: '#A8C4D9',
    type: '#A8C4D9',
    operator: '#9EA8AC',
    punctuation: '#8B979B',
    tag: '#E86B6B',
    attribute: '#B5A8E0',
    regexp: '#9FD9CE',
    decorator: '#B5A8E0',
    invalid: '#E86B6B',
  },
});
